services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4599:4510-4599"
    environment:
      - LOCALSTACK_SERVICES=sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=localstack-access-key
      - AWS_SECRET_ACCESS_KEY=localstack-secret-key
      - AWS_DEFAULT_REGION=ap-northeast-1
      - LS_ACCOUNT_ID=123456
    volumes:
    - ./localstack-init:/var/localstack

  springboot-app:
    build:
      context: ./springlocalstack 
      dockerfile: Dockerfile       
    volumes:
      - ./springlocalstack:/app  
    ports:
      - "8080:8080"                
    environment:
      - SPRING_PROFILES_ACTIVE=dev  
    stdin_open: true                
    tty: true
